{% set name = "bash" %}
{% set version = "5.1.016" %}
{% set _patch_level = version.split(".")[2]|int %}
{% set base_version = version.split(".")[0]+"."+version.split(".")[1] %}

### From ArchLinux, better than nothing (less good than .sigs, see later)

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ base_version }}.tar.gz
    sha256: b4a80f2ac66170b2913efbfb9f2594f1f76c7b1afd11f799e22035d63077fb4d
    patches:
      # These are from https://ftp.gnu.org/gnu/bash/bash-5.1-patches/
      - gnu-patches/bash51-001
      - gnu-patches/bash51-002
      - gnu-patches/bash51-003
      - gnu-patches/bash51-004
      - gnu-patches/bash51-005
      - gnu-patches/bash51-006
      - gnu-patches/bash51-007
      - gnu-patches/bash51-008
      - gnu-patches/bash51-009
      - gnu-patches/bash51-010
      - gnu-patches/bash51-011
      - gnu-patches/bash51-012
      - gnu-patches/bash51-013
      - gnu-patches/bash51-014
      - gnu-patches/bash51-015
      - gnu-patches/bash51-016

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - bison
  host:
    - readline
  run:
    - readline

test:
  requires:
    - ripgrep
  commands:
    - bash --version | rg {{ base_version }}.{{ _patch_level }}

about:
  home: https://www.gnu.org/software/bash/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Bourne Again Shell'
  description: |
    Bash is the GNU Project's shell. Bash is the Bourne Again SHell.
    Bash is an sh-compatible shell that incorporates useful features
    from the Korn shell (ksh) and C shell (csh). It is intended to
    conform to the IEEE POSIX P1003.2/ISO 9945.2 Shell and Tools standard.
    It offers functional improvements over sh for both programming and
    interactive use. In addition, most sh scripts can be run by Bash
    without modification.
  doc_url: https://www.gnu.org/software/bash/manual/
  dev_url: https://git.savannah.gnu.org/cgit/bash.git/

extra:
  recipe-maintainers:
    - scopatz
    - mingwandroid
    - matthiasdiener
